### ISSUE TITLE
Add Shields.io VS Code Rating Badge to Readme

### ISSUE THREAD

**Issue by SgiobairOg** [SgiobairOg/color-vision#1]
Would like to spruce up the Readme with some badges from Shields.IO

Please add the VS Code Marketplace Ratings badge [found here](https://shields.io/category/rating) to the README.md file after the opening title.

If you're new to submitting code changes and pull requests through Git I'm more than happy to help you get started.

**Comment by andregallacci** [comment]
Hello! I did.. #5 
Can you take a look?

**Comment by SgiobairOg** [comment]
Will do, thanks!
