### ISSUE TITLE
Add Shields.io VS Code Version Badge to README

### ISSUE THREAD

**Issue by SgiobairOg** [SgiobairOg/color-vision#2]
Would like to spruce up the Readme with some badges from Shields.IO

Please add the VS Code Marketplace Version badge [found here](https://shields.io/category/version) to the README.md file after the opening title.

If you're new to submitting code changes and pull requests through Git I'm more than happy to help you get started.

**Comment by fsjoyti** [comment]
I added version badge in Pull Request #6

**Comment by SgiobairOg** [comment]
Thank you!
