### ISSUE TITLE
Add Preview Animation to the README

### ISSUE THREAD

**Issue by SgiobairOg** [SgiobairOg/color-vision#3]
An animated preview of the extension functionality is being created for display in the README. 

The image should be added to the README at the end of the Features section. Will add the link to the issue when the image is available.

If you're new to making code edits and pull requests through Git, I'm happy to help.

**Comment by pradipta007** [comment]
Hi, Can i take it up?

**Comment by SgiobairOg** [comment]
Absolutely, I'll go ahead and assign you. Been a bit sick today but will hopefully have the image soon.

**Comment by SgiobairOg** [comment]
Alright, images are up, let's use `resources/images/usage_15102019_512.gif`

For the alt text, let's use `Example usage of the Color Vision extension showing color swatches being added to HEX and RGB color definitions`
